### PR TITLE
additg render_template html file

### PR DESCRIPTION
**Pull request by noamfi**
#76

### CODE REVIEW

**Comment by IlanZuckerman** [comment]
The failure is in the test of curl the server (to check its up)

I think that the reason is that the following line isnt right:
return render_template('/home.html')

the path of home.html is templates/home.html 
so i think this should be correct:
return render_template('templates/home.html')

**Comment by lioramilbaum** [comment]
@noamfi Have you tested the code before submitting the PR?

**Comment by noamfi** [comment]
I have tested it locally on my computer and it was successful

**Comment by IlanZuckerman** [comment]
I've just verified the changes Noam did in this branch by running the app.py locally. All seems fine. But the CI keeps failing on http_get_test.sh
I suggest running again the CI, this time with debugging enabled for the http_get_test.sh in order to understand why it fails.

To add debug for shell script:

set -x
..code to debug...
set +x

**Comment by lioramilbaum** [comment]
It might be related to the directory where the application is executed by Travis. You can use the templates attribute when instantiating the Flask app.

**Comment by Omeramsc** [comment]
I debugged the script, it works fine:
```
+ exp_response=200
++ curl -o /dev/null -s -w '%{http_code}\n' http://localhost:5000
+ [[ 200 = 200 ]]
+ exit 0
```

**Comment by noamfi** [comment]
thanks @Omeramsc how do I apply the changes now?

**Comment by Omeramsc** [comment]
@noamfi  I'm not sure I understand... 
I just tested the script with your code to see if it runs, and it does, but I didn't change anything in the code, so the reason for which Travis fails remains a mystery...

BUT
I tested the script again, with your changes, on the ubuntu machine and got this message:
```+ exp_response=200
+ curl -o /dev/null -s -w %{http_code}\n http://localhost:5000
+ [[ 200 = 200 ]]
/vagrant/tests/http_get_test.sh: 3: /vagrant/tests/http_get_test.sh: [[: not found
+ exit 1
```
Any Idea why the ubunto machine react differently to the same script?

**Comment by IlanZuckerman** [comment]
What changes you want to apply, Noam? We still dont know why The CI keeps failing. Omer just debugged hist shell script. Nothing has changed.
I suggest  reverting the app.py to static html (as it was before) and see if the CI fails again.
If that succeeds, then we will know that there is an issue around templates folder, and then we should try what Liora suggested by Triggering the app.py with template argument (we can see later how to do that).

**Comment by Omeramsc** [comment]
UPDATE: script runs fine on ubuntu machine when I delete 1 pair or "[]". should I update it then? @IlanZuckerman  @noamfi  @lioramilbaum

**Comment by IlanZuckerman** [comment]
Fine with me, Omer, lets update it. You can open a new PR for that, and fix it before Noam PR. In that case Noam will have to rebase his branch.

**Comment by noamfi** [comment]
looking at Travis "Raw log" I see error: 31mCould not open requirements file: [Errno 2] No such file or directory: '/vagrant/requirements.txt'

is it possible that that is the porblem?
if yes does it meant that app.py is not running on CI?

**Comment by IlanZuckerman** [comment]
> looking at Travis "Raw log" I see error: 31mCould not open requirements file: [Errno 2] No such file or directory: '/vagrant/requirements.txt'
> 
> is it possible that that is the porblem?
> if yes does it meant that app.py is not running on CI?

You are right, i also see this error of requirements.txt not found. That is very weird.

**Comment by lioramilbaum** [comment]
It is not weird at all. vagrant is not running in Travis CI. Therefor, the requirements.txt file in a different folder. You should use a different path when running in Travis environment.

**Pull request merged**
