### PR TITLE
Bootstrap.sh

### PR DESCRIPTION
**Pull request by kittyweg**
fix #60

### CODE REVIEW

**Comment by kittyweg** [comment]
1 - The first commit (the one you said "have mistakenly linked the issue to itself in the previous comment." ) was indeed a mistake that I didn't know how to undo.
2 - Edited fix #60 but still no linked issues
3 - I ran the code and as you pointed, it did not work, giving the following error: 
[kweg@kweg baboon]$ sh ./bootstrap.sh 
./bootstrap.sh: line 3: apt-get: command not found
./bootstrap.sh: line 4: apt-get: command not found
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt

Looking into it.

**Comment by lioramilbaum** [comment]
1. delete the comment
2. you are linking the PR to itself instead to the issue.
3. bootstrap.sh is not supposed to run on your host (laptop). It is supposed to run on the guest which is ubuntu.

**Comment by kittyweg** [comment]
I don't have an Ubuntu guest to test the bootstrap.sh, it is still not working with libvirt.

**Comment by lioramilbaum** [comment]
I know. Please take care of till our next session.

**Pull request closed without merging**
